title: Cloud Scripts
email: bennowaldmann@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Short and sweet scripts, thoughts and ideas for Cloud development, DevOps and Programming. 
baseurl: "/cloudscripts" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  bennowaldmann

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
